---
deployment:
  tasks:
    - export DEPLOYPATH=/home/te1579qh1j7x/public_html/
    - /bin/cp navigationcode.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R logo $DEPLOYPATH
    - /bin/cp navigationcode.css $DEPLOYPATH